### ISSUE TITLE
Items Respawning

### ISSUE THREAD

**Issue by hwn2020** [WulfMarius/Better-Placing#1]
TLD v1.12(32511)
The Better-Placing v1.2.0 causes items such as curtains, stools, crates to respawn after leaving a building or loading the game.  I have tried this on old saves, as well as new games and everytime you leave a building, the items you broke down inside have respawned.

**Comment by WulfMarius** [comment]
Confirmed!

Fixed with release 1.2.1.
Thank you for reporting this - well spotted!
