### ISSUE TITLE
Item Respawning

### ISSUE THREAD

**Issue by hwn2020** [WulfMarius/Better-Placing#2]
TLD v.1.16

I am using the most recent Better Placing and there is a chair that is respawning in the ML Camp office, after being broken down.  I have broken down other chairs, but that one is the only one I have noticed respawning.

![desktop screenshot 2017 12 09 - 16 45 26 32](https://user-images.githubusercontent.com/33557014/33800667-d2a53a26-dd01-11e7-892a-f62c92c33679.png)

**Comment by WulfMarius** [comment]
Confirmed!
I don't really understand what made that one so special, but it's fixed for the next release, nonetheless.

Thanks for reporting!
