### ISSUE TITLE
trapper's cabin is bugged with old saves

### ISSUE THREAD

**Issue by cola98765** [WulfMarius/Better-Placing#3]
I was using Umod for placing items before, but after last update I had to find another mod that would work with fireplaces.

The issue is that when I enter that location (by loading save or using door) with this mod installed I start falling through map.
When i reach fireplace I get teleported back up, however there are invisible wall, you can walk through normal walls, and some furniture is misplaced.

https://i.imgur.com/7zycpRE.jpg
https://i.imgur.com/IqKL59O.jpg
on the screenshots you can see Umod UI but bug occurs also when this mod is the only one installed

**Comment by WulfMarius** [comment]
Fixed in version 2.1.1.

Thanks for reporting!
