### ISSUE TITLE
Thanks for update!

### ISSUE THREAD

**Issue by Whisper001** [WulfMarius/Better-Placing#4]
I would  like to  ask how to start if I want to make my own mod: for example, open cans with a hacksaw, change the attributes of some things and so on. I'm familiar with Unity and C#, but I do not really know where to get information how I can change the game.

**Comment by WulfMarius** [comment]
Hi!

The first step would be to use a decompiler for .net (like [dotpeek](https://www.jetbrains.com/decompiler/)) to take a look at how the game actually works.
This allows you to identify methods and classes that define/implement the behaviour you want to target.

Then you use [Harmony](https://github.com/pardeike/Harmony) patches to intercept those methods and either completely detour around them or change their parameters/results.

Then you compile all your changes into a DLL and let the [ModLoader](https://github.com/zeobviouslyfakeacc/ModLoaderInstaller) load your DLL and automatically apply your Harmony patches.


This is obviously very simplified, but really all you need to do to make a first small mod. If you take a look at https://github.com/WulfMarius/Durable-Whetstone/tree/master/src you'll see that this mod doesn't really contain much more than the Harmony patch.

There's also a discord server specifically for modding TLD: https://discord.gg/BwrWFwT
Probably easier to get more help there and also more people who can help out if someone's not available.

HTH
