### ISSUE TITLE
V1.35.38054 Update Nerfed the Placement Mechanics

### ISSUE THREAD

**Issue by ShabbirSS** [WulfMarius/Better-Placing#6]
Objects start floating when you try to stack placed items

**Comment by WulfMarius** [comment]
Could you provide at least some basic information, like 
* what version of Better-Placing are you using
* which items float
* when and where do they float
* maybe a screenshot

It's extremely difficult to do anything when I don't even know what to look for.

**Comment by EmberMordu** [comment]
I just found an example of when the objects start floating. I am using version 2.1.2 and I was placing tinder plugs on a table and when they were stacking, the top tinder plug was floating. I don't know if this is the only item that floats, but it's at least one.

**Comment by ShabbirSS** [comment]
Hi Guys...

Better Placing 2.1.2...Game version 1.35 38054

it does not mess up the gameplay tho,the game is still very playable. i noticed that objects do float when placing, but sometimes they get placed neatly too. its kinda random-ish

heres some screenshots...

![screen_0b107970-f2de-45f4-a14b-c3b2586621d2_hi](https://user-images.githubusercontent.com/40413749/43250058-b583b020-90bc-11e8-878f-85f9ed1359e7.png)
![screen_1a17c251-1388-4619-a95e-6e509fe6551d_hi](https://user-images.githubusercontent.com/40413749/43250065-bad8c34e-90bc-11e8-80ca-c750c098973c.png)
![screen_4a4d85ee-0d87-4c86-ab5a-5afe1a7bd55d_hi](https://user-images.githubusercontent.com/40413749/43250073-c244d6f4-90bc-11e8-85fc-e7c34d03e853.png)
![screen_40ab455a-4a76-4f03-8628-e647222d2e1f_hi](https://user-images.githubusercontent.com/40413749/43250076-c4548b92-90bc-11e8-9779-abde8a6e7732.png)
![screen_042e544f-48e5-473c-a338-c72bba40d242_hi](https://user-images.githubusercontent.com/40413749/43250085-ca4a54b4-90bc-11e8-9e0c-e8f32716b168.png)
![screen_907d41ac-8152-4b45-a305-c4245e3c1a4a_hi](https://user-images.githubusercontent.com/40413749/43250097-d2e4d9a0-90bc-11e8-9dd9-01007e088dba.png)
![screen_e6e02b88-8252-4b53-a93b-e3b676e8033c_hi](https://user-images.githubusercontent.com/40413749/43250121-e2eb2624-90bc-11e8-9b14-15190f73d603.png)

Once again,have to thank you for the mods WulfMarius, taking your time to make our gameplay in tld better

**Comment by WulfMarius** [comment]
Recent bug fixes and improvements should have fixed all these problems.
