### ISSUE TITLE
Food items glitch into item below it when entering and exiting space

### ISSUE THREAD

**Issue by charkshark** [WulfMarius/Better-Placing#7]
Stuff like MRE and all canned foods can be stacked, but when I exit and enter the Trapper's Cabin, they end up inside the item below it. I can get them back just by right clicking just fine, but it guess their position isn't saved when they're stacked on top of an item? 

![20180916010104_1](https://user-images.githubusercontent.com/43308878/45593097-15407900-b94c-11e8-8262-caeb21fe0a79.jpg)

I was trying to hold L and clicking while doing it, but I wasn't too sure what that was doing. 

Thank you very much for this mod by the way

**Comment by WulfMarius** [comment]
I can't reproduce this here.

Are you using the latest version?
If you're not missing an update, the log file might show something.

**Comment by charkshark** [comment]
Sorry for late reply. Yeah i downloaded it using the mod downloader, assuming that downloads the most recent version of every mod. Where can I check the log file?

**Comment by kauffy** [comment]
@WulfMarius I'm seeing this same behavior, except it's with all stacks. It's as though the height/Z isn't stored when you leave an area, and when you return, everything is collapsed just to its X/Y.

AFAIK, I am using the latest everything-- I just got the mod stuff working today for the first time.

EDIT, to add: I am using Linux.

**Comment by WulfMarius** [comment]
I have a savegame where I can reproduce this.

**Comment by WulfMarius** [comment]
My savegame is no longer having this problem.  
So it seems like this is only happening in certain situations or even randomly.

If you have a savegame that produces this regularly, you can try to upload it here and maybe that'll allow me to keep working on this.

**Comment by kauffy** [comment]
I just verified (my machine was down for the last few days). It's still happening on one of my saves.

Could this be Linux v. Windows?
[sandbox12.zip](https://github.com/WulfMarius/Better-Placing/files/2454099/sandbox12.zip)

**Comment by WulfMarius** [comment]
Found the issue thanks to the savegame.  
Ultimately it depends on where the items are stacked, so that's why I had trouble reproducing this sometimes.

Release 2.1.3 is out and should solve this.
